del *.Administrator
del *.bak
del *.zhxx
del *.uvopt
del output\*.i
del output\*.htm
del output\*.__i
del output\*.obj
del output\*.lst
del output\*.plg
del output\*.iex
del output\*.m51
del output\*.lnp
del output\ecbm
del output\*._ia
del output\*.SRC
del output\*.ls1